//
// Created by coldmint on 2026/2/26.
//

#include "PreloadColors.h"

#include "core/mod/ResourceRef.h"
#include "core/mod/Resource.h"
#include "core/mod/ResourceLocator.h"

void glimmer::PreloadColors::LoadAllColors(const ResourceLocator *resourceLocator) {
    ColorResource text;
    text.r = 245;
    text.g = 245;
    text.b = 240;
    text.a = 255;
    textColor = LoadColor(resourceLocator, "text", &text)->ToSDLColor();
    ColorResource textDisabled;
    textDisabled.r = 120;
    textDisabled.g = 120;
    textDisabled.b = 110;
    textDisabled.a = 255;
    textDisabledColor = LoadColor(resourceLocator, "text_disabled", &textDisabled)->ToSDLColor();
    ColorResource textLink;
    textLink.r = 80;
    textLink.g = 160;
    textLink.b = 220;
    textLink.a = 255;
    textLinkColor = LoadColor(resourceLocator, "text_link", &textLink)->ToSDLColor();
    ColorResource textSelectedBg;
    textSelectedBg.r = 180;
    textSelectedBg.g = 120;
    textSelectedBg.b = 60;
    textSelectedBg.a = 255;
    textSelectedBgColor = LoadColor(resourceLocator, "text_selected_bg", &textSelectedBg)->ToSDLColor();
    ColorResource background;
    background.r = 45;
    background.g = 45;
    background.b = 40;
    background.a = 255;
    backgroundColor = LoadColor(resourceLocator, "background", &background)->ToSDLColor();
    ColorResource border;
    border.r = 70;
    border.g = 70;
    border.b = 65;
    border.a = 255;
    borderColor = LoadColor(resourceLocator, "border", &border)->ToSDLColor();
    ColorResource borderShadow;
    borderShadow.r = 20;
    borderShadow.g = 20;
    borderShadow.b = 15;
    borderShadow.a = 180;
    borderShadowColor = LoadColor(resourceLocator, "border_shadow", &borderShadow)->ToSDLColor();
    ColorResource separator;
    separator.r = 60;
    separator.g = 60;
    separator.b = 55;
    separator.a = 255;
    separatorColor = LoadColor(resourceLocator, "separator", &separator)->ToSDLColor();
    ColorResource separatorHovered;
    separatorHovered.r = 90;
    separatorHovered.g = 80;
    separatorHovered.b = 60;
    separatorHovered.a = 255;
    separatorHoveredColor = LoadColor(resourceLocator, "separator_hovered", &separatorHovered)->ToSDLColor();
    ColorResource separatorActive;
    separatorActive.r = 120;
    separatorActive.g = 100;
    separatorActive.b = 70;
    separatorActive.a = 255;
    separatorActiveColor = LoadColor(resourceLocator, "separator_active", &separatorActive)->ToSDLColor();
    ColorResource frameBg;
    frameBg.r = 55;
    frameBg.g = 55;
    frameBg.b = 50;
    frameBg.a = 255;
    frameBgColor = LoadColor(resourceLocator, "frame_bg", &frameBg)->ToSDLColor();
    ColorResource frameBgHovered;
    frameBgHovered.r = 75;
    frameBgHovered.g = 70;
    frameBgHovered.b = 60;
    frameBgHovered.a = 255;
    frameBgHoveredColor = LoadColor(resourceLocator, "frame_bg_hovered", &frameBgHovered)->ToSDLColor();
    ColorResource frameBgActive;
    frameBgActive.r = 85;
    frameBgActive.g = 75;
    frameBgActive.b = 65;
    frameBgActive.a = 255;
    frameBgActiveColor = LoadColor(resourceLocator, "frame_bg_active", &frameBgActive)->ToSDLColor();
    ColorResource button;
    button.r = 90;
    button.g = 85;
    button.b = 70;
    button.a = 255;
    buttonColor = LoadColor(resourceLocator, "button", &button)->ToSDLColor();
    ColorResource buttonHovered;
    buttonHovered.r = 110;
    buttonHovered.g = 105;
    buttonHovered.b = 85;
    buttonHovered.a = 255;
    buttonHoveredColor = LoadColor(resourceLocator, "button_hovered", &buttonHovered)->ToSDLColor();
    ColorResource buttonActive;
    buttonActive.r = 70;
    buttonActive.g = 65;
    buttonActive.b = 50;
    buttonActive.a = 255;
    buttonActiveColor = LoadColor(resourceLocator, "button_active", &buttonActive)->ToSDLColor();
    ColorResource scrollbarBg;
    scrollbarBg.r = 50;
    scrollbarBg.g = 50;
    scrollbarBg.b = 45;
    scrollbarBg.a = 255;
    scrollbarBgColor = LoadColor(resourceLocator, "scrollbar_bg", &scrollbarBg)->ToSDLColor();
    ColorResource scrollbarGrab;
    scrollbarGrab.r = 80;
    scrollbarGrab.g = 75;
    scrollbarGrab.b = 60;
    scrollbarGrab.a = 255;
    scrollbarGrabColor = LoadColor(resourceLocator, "scrollbar_grab", &scrollbarGrab)->ToSDLColor();
    ColorResource scrollbarGrabHovered;
    scrollbarGrabHovered.r = 100;
    scrollbarGrabHovered.g = 95;
    scrollbarGrabHovered.b = 75;
    scrollbarGrabHovered.a = 255;
    scrollbarGrabHoveredColor = LoadColor(resourceLocator, "scrollbar_grab_hovered", &scrollbarGrabHovered)->ToSDLColor();
    ColorResource scrollbarGrabActive;
    scrollbarGrabActive.r = 60;
    scrollbarGrabActive.g = 55;
    scrollbarGrabActive.b = 40;
    scrollbarGrabActive.a = 255;
    scrollbarGrabActiveColor = LoadColor(resourceLocator, "scrollbar_grab_active", &scrollbarGrabActive)->ToSDLColor();
    ColorResource inputTextCursor;
    inputTextCursor.r = 200;
    inputTextCursor.g = 120;
    inputTextCursor.b = 40;
    inputTextCursor.a = 255;
    inputTextCursorColor = LoadColor(resourceLocator, "input_text_cursor", &inputTextCursor)->ToSDLColor();
    ColorResource navCursor;
    navCursor.r = 220;
    navCursor.g = 140;
    navCursor.b = 50;
    navCursor.a = 255;
    navCursorColor = LoadColor(resourceLocator, "nav_cursor", &navCursor)->ToSDLColor();
    ColorResource header;
    header.r = 50;
    header.g = 48;
    header.b = 42;
    header.a = 255;
    headerColor = LoadColor(resourceLocator, "header", &header)->ToSDLColor();
    ColorResource headerHovered;
    headerHovered.r = 75;
    headerHovered.g = 70;
    headerHovered.b = 60;
    headerHovered.a = 255;
    headerHoveredColor = LoadColor(resourceLocator, "header_hovered", &headerHovered)->ToSDLColor();
    ColorResource headerActive;
    headerActive.r = 85;
    headerActive.g = 78;
    headerActive.b = 65;
    headerActive.a = 255;
    headerActiveColor = LoadColor(resourceLocator, "header_active", &headerActive)->ToSDLColor();
    ColorResource consoleBackgroundColor;
    consoleBackgroundColor.r = 30;
    consoleBackgroundColor.g = 30;
    consoleBackgroundColor.b = 25;
    consoleBackgroundColor.a = 255;
    console.backgroundColor = LoadColor(resourceLocator, "console/background", &consoleBackgroundColor)->ToSDLColor();
    ColorResource consoleTitleColor;
    consoleTitleColor.r = 220;
    consoleTitleColor.g = 140;
    consoleTitleColor.b = 50;
    consoleTitleColor.a = 255;
    console.titleColor = LoadColor(resourceLocator, "console/title", &consoleTitleColor)->ToSDLColor();
    ColorResource consoleKeywordColor;
    consoleKeywordColor.r = 60;
    consoleKeywordColor.g = 180;
    consoleKeywordColor.b = 220;
    consoleKeywordColor.a = 255;
    console.keywordColor = LoadColor(resourceLocator, "console/keyword", &consoleKeywordColor)->ToSDLColor();
    ColorResource consoleTextColor;
    consoleTextColor.r = 240;
    consoleTextColor.g = 240;
    consoleTextColor.b = 230;
    consoleTextColor.a = 255;
    console.textColor = LoadColor(resourceLocator, "console/text", &consoleTextColor)->ToSDLColor();
    ColorResource errorAccentColor;
    errorAccentColor.r = 191;
    errorAccentColor.g = 62;
    errorAccentColor.b = 255;
    errorAccentColor.a = 255;
    error.accentColor = LoadColor(resourceLocator, "errorTexture/accent", &errorAccentColor)->ToSDLColor();
    ColorResource errorBaseColor;
    errorBaseColor.r = 15;
    errorBaseColor.g = 15;
    errorBaseColor.b = 15;
    errorBaseColor.a = 255;
    error.baseColor = LoadColor(resourceLocator, "errorTexture/base", &errorBaseColor)->ToSDLColor();
    ColorResource focusTileBorderColor;
    focusTileBorderColor.r = 245;
    focusTileBorderColor.g = 245;
    focusTileBorderColor.b = 240;
    focusTileBorderColor.a = 255;
    game.focusTileBorderColor = LoadColor(resourceLocator, "game/focus_tile_border", &focusTileBorderColor)->ToSDLColor();
}

glimmer::ColorResource *glimmer::PreloadColors::LoadColor(const ResourceLocator *resourceLocator,
                                                          const std::string &key, ColorResource *defaultColor) {
    ResourceRef resourceRef;
    resourceRef.SetSelfPackageId(RESOURCE_REF_CORE);
    resourceRef.SetResourceType(RESOURCE_TYPE_COLOR);
    resourceRef.SetResourceKey(key);
    return resourceLocator->FindColorResource(resourceRef, defaultColor);
}
