# Make a copy of this file and rename it to config.cmake
# 将这个文件复制一份并重命名到config.cmake

# Whether to enable X11 support (for the Linux platform)
# 是否启用X11支持（用于Linux平台）
option(X11_SUPPORT "Enable X11 support" OFF)
# Enable unit testing compilation
# 启用单元测试编译
option(UNIT_TEST "Enable unit test" OFF)

# The repository address of PackSigner
# PackSigner的仓库地址
# https://github.com/Cold-Mint/GlimmerWorksPackSigner

# Path of the signed executable file package
# 包签名可执行文件路径
set(PACK_SIGNER_EXE "")
# Private key path (used for data packet signature, generated by packSigner)
# 私钥路径（用于数据包签名，通过packSigner生成）
set(SIGN_PRIVATE_KEY "${PROJECT_SOURCE_DIR}/keys/ed25519.private")
# Shared key path (used for data packet signature, generated by packSigner)
# 共钥路径（用于数据包签名，通过packSigner生成）
set(SIGN_PUBLIC_KEY "${PROJECT_SOURCE_DIR}/keys/ed25519.public")