config_version = 1

# Runtime data storage path
# 运行时数据存放路径
runtime_path = "runtime"

[window]
# Window width (pixels)
# 窗口宽度（像素）
width = 1920
# Window height (pixels)
# 窗口高度（像素）
height = 1080
# Allow window resizing
# 允许窗口调整大小
resizable = true
# Target framerate (FPS)
# 目标帧率（帧/秒）
framerate = 60.0
# UI scaling factor
# UI界面缩放比例
ui_scale = 1.0
# Enable vertical sync (VSync)
# 启用垂直同步
vsync = true

[audio]
# Master volume
# 主音量
master_volume = 1.0
# channels
# 声道数
channels = 2
#freq
#采样率
freq = 44100

# Audio data format
# 音频数据格式
# Optional values: F32, S32, S16, U8
# 可选值：F32, S32, S16, U8
#
# F32 ：Floating-point 32-bit | 32位浮点型
#       Best quality, no distortion, modern standard(Default)
#       音质最好、无失真、现代游戏标准(默认)
#
# S16 ：Signed integer 16-bit | 16位整型
#       Lightweight, good compatibility, low CPU usage
#       轻量省电、兼容性强、低配设备首选
#
# S32 ：Signed integer 32-bit | 32位整型
#       High precision, but not necessary for games
#       精度高，但游戏中无明显优势
#
# U8 ：Unsigned 8-bit | 8位无符号型
#       Lowest quality, only for retro/chiptune
#       音质差，仅用于复古/8-bit音效
#
format = "F32"

# Audio track group configuration (pre-allocate fixed track pool for each audio type, reuse to avoid performance issues)
# 音频轨道组配置（按音频类型分配固定轨道池，预创建复用，避免频繁创建销毁）
[[audio.track]]
#BGM
type = 0
#The number of pre-allocated orbits of this type
#该类型预分配的轨道数量
track_count = 1
volume = 1.0

[[audio.track]]
#AMBIENT
#环境音效
type = 1
track_count = 20
volume = 1.0

[world]
# Preload config for off-screen chunks (view range expansion)
# 屏幕外区块预加载配置（视野范围扩展）
# Preload chunk outer radius (view range expansion)
# 区块预加载外扩范围（视野范围扩展）
preload_chunk_radius = 1.0
# Preload structure radius (terrain/structure data pre-calc)
# 结构预加载范围（地形/结构数据预计算）
preload_structure_radius = 5.0

[command]
# Number of chunks traversed in the positive/negative X direction when using the `locate biome` command.
# 使用 locate biome 命令时，沿 X 轴正 / 负方向遍历的区块数量。
locate_max_radius_search_chunks = 2048

[mods]
# Data pack storage path
# 数据包存储路径
data_pack_path = "mods/data_packs"
# Resource pack storage path
# 资源包存储路径
resource_pack_path = "mods/resource_packs"
# Enabled data packs (list of pack IDs)
# 启用的数据包（包ID列表）
enabled_data_pack = ["glimmerworks"]
# Enabled resource packs (list of pack IDs)
# 启用的资源包（包ID列表）
enabled_resource_pack = ["glimmerworks_res"]
# Supported audio formats
# 支持的音频格式
# The SDL_mix library used in the game can decode more audio formats. However, in order to standardize the audio format used, it is restricted here to only load the following types.
# 游戏使用的SDL_mix库，虽然能够解码更多格式的音频，但是为了规范使用的音频格式，所以在这里限制了只能加载以下类型。
# The audio that comes earlier will be loaded first. For example, if supportedAudioFormats = ["ogg", "wav"], when searching for "block_brack", it will first search for "block_brack.ogg" and then "block_brack.wav".
# 排在前面的音频会被优先加载。例如supportedAudioFormats = ["ogg"，"wav"]，查找"block_brack"时，会优先搜索"block_brack.ogg"其次是"block_brack.wav"
# The release build has been trimmed to support only OGG. To support additional formats, you need to modify the CMakeLists.txt and recompile the game.
# 发行版已被裁减为仅支持ogg，支持更多格式需要修改CMakeLists.txt重新编译游戏。
supported_audio_formats = ["ogg"]
# Supported texture formats
# 支持的纹理格式
# The textures that come earlier will be loaded first.
# 排在前面的纹理会被优先加载。
# The release build has been trimmed to support only PNG. To support additional formats, you need to modify the CMakeLists.txt and recompile the game.
# 发行版已被裁减为仅支持png，支持更多格式需要修改CMakeLists.txt重新编译游戏。
supported_texture_formats = ["png"]

[debug]
# Show debug panel in game
# 游戏内显示调试面板
display_debug_panel = false
# Render Box2D collision shapes
# 渲染Box2D物理碰撞形状
display_box2d_shape = false
# Draw the boundaries of the area for dragging and dropping
# 绘制拖拽的区域边界
display_draggable_target = false
# Display elevation map
# 显示海拔图
display_elevation_map = false
# Display temperature map
# 显示温度图
display_temp_map = false
# Display humidity map
# 显示湿度图
display_humidity_map = false
# Display erosion map
# 显示侵蚀图
display_erosion_map = false
# Display weirdness map
# 显示奇异度图
display_weirdness_map = false

[console]
# Maximum number of console history entries to save (0 = disable history function)
# 控制台历史记录最大保存条数（0 = 禁用历史记录功能）
max_history_entries = 100

[hotkey_f2]
command_group = [["screenShot create"]]

[hotkey_f12]
command_group = [
    ["config set debug.display_debug_panel toggle","config commit"],
]

[hotkey_f11]
command_group = [
    ["config set debug.display_box2d_shape toggle","config commit"],
]

[hotkey_f10]
command_group = [
    ["config set debug.display_elevation_map toggle", "config commit"],
]

[hotkey_f9]
command_group = [
    ["config set debug.display_temp_map toggle", "config commit"],
]

[hotkey_f8]
command_group = [
    ["config set debug.display_erosion_map toggle", "config commit"],
]

[hotkey_f7]
command_group = [
    ["config set debug.display_weirdness_map toggle", "config commit"],
]

[hotkey_f6]
command_group = [
    ["config set debug.display_humidity_map toggle", "config commit"],
]