# Make a copy of this file and rename it to config.cmake
# 将这个文件复制一份并重命名到config.cmake

# Whether to enable X11 support (for the Linux platform)
# 是否启用X11支持（用于Linux平台）
option(X11_SUPPORT "Enable X11 support" OFF)

# Full path to the host protoc executable (required for cross-compilation)
# 如果是交叉编译，那么必须得由用户指定protoc。
set(PROTOC_EXECUTABLE_PATH "")

# The repository address of PackSigner
# PackSigner的仓库地址
# https://github.com/Cold-Mint/GlimmerWorksPackSigner

# Path of the signed executable file package
# 包签名可执行文件路径
set(PACK_SIGNER_EXE "")
# Private key (used for data packet signature, generated by packSigner)
# 私钥（用于数据包签名，通过packSigner生成）

set(SIGN_PRIVATE_KEY "")
# Shared key(used for data packet signature, generated by packSigner)
# 共钥（用于数据包签名，通过packSigner生成）
set(SIGN_PUBLIC_KEY "")