ability_item_is_null = "Abilityアイテムが空です。"
area_marker_tip = "幅：{}\n高さ：{}\n面積：{}\n"
awake_body_count = "アクティブな物理コライダー数：{}"
can_mine_block_tip = "ブロックを掘削できます"
can_mine_wall_tip = "壁を解体できます"
cancel = "キャンセル"
cant_find_object = "ゲームオブジェクトが見つかりません。"
chain_mining_tip = "{}チェーンマイニング半径"
command_info = "合計{}個のコマンドが登録されています："
command_is_empty = "コマンドが空です"
command_not_found = "コマンドが見つかりません：{}"
composable_item_is_null = "合成可能なアイテムが空です。"
confirm = "確定"
console = "コンソール"
create_world = "ワールド作成"
delete_game = "セーブデータを削除"
efficiency_tip = "{}％の掘削効率"
executed_success = "{}の実行に成功しました"
execution_failed = "{}の実行に失敗しました"
exit_game = "ゲームを終了"
failed_to_load_license = "ローカルのLICENSEファイルの読み込みに失敗しました。\nこのファイルは本プログラムの各ディストリビューションに含まれるべきです。\n紛失している場合は、インストールを確認するか、オンラインでライセンスを確認してください：\nhttps://github.com/Cold-Mint/GlimmerWorks/blob/master/LICENSE"
file_writing_failed = "ファイル{}の書き込みに失敗しました。"
folder_creation_failed = "フォルダ{}の作成に失敗しました。"
fumble_tip = "{}％滑り手"
get_actual_path_error = "実パスの取得に失敗しました。"
insufficient_parameter_length = "パラメータ長が不足しています。最小{}ですが、実際は{}です。"
item_container_is_null = "アイテムコンテナが空です。"
item_id_not_found = "アイテムIDが見つかりません。"
item_resource_is_null = "itemResourceが空です。"
load_game = "ゲーム読み込み"
loot_table_not_found = "戦利品表IDが見つかりませんでした。"
map_manifest_is_null = "mapManifestの読み込みに失敗しました。"
min_x_is_greater_than_max_x = "最小X座標は最大X座標より大きくできません。"
mods = "モッド"
pause = "一時停止"
precision_mining_tip = "精密採掘"
random = "ランダム"
restore = "復帰"
save_and_exit = "保存して終了"
saved_games = "保存済みゲーム"
saves_list = "セーブデータリスト"
screenshot_saved_failed = "スクリーンショットの保存に失敗しました{}。"
screenshot_saved_success = "スクリーンショットは{} に保存されました。"
seed = "シード"
settings = "設定"
slogans = [
    "AIにありがとうは無駄ですか？",
    "ゲームは商品じゃない！",
    "資本に飼い慣らされないクリエイション。",
    "世界はオープンソース、創造は無限。",
    "え？全部TOMLに隠れてるよ",
    "普通に見えるファイル、開いてみたことある？",
    "ガチャやピティシステム、本当に好きですか？",
    "誰も同じ世界には二度と踏み入れない。",
    "ルールの一部は、ボタン一つで書き換えられる。",
    "give abilityItem glimmerworks:area_marker",
    "にゃ～",
    "Ciallo～(∠・ω< )⌒☆",
    "私はいずれ塵となる、でもオープンソースの世界は永遠に生き続ける。",
    "ねえ、一緒に嘘を紡いでみる？",
    "ゆっくりでいい。集中力だって超能力なんだ。",
    "本当の楽しさは、確率で決めるものじゃない。",
    "自分の世界で、真剣に生きても大丈夫。",
    "夢は軽く、生活は重い。",
    "今夜の飯はどこだ？"
]
start_game = "ゲーム開始"
teleport_entity = "IDが{}のエンティティをx={},y={}にテレポートしました。"
tile_resource_is_null = "tileResourceが空です。"
unknown_asset_type = "未知のアセットタイプです。"
unknown_command_parameters = "未知のコマンドパラメータです。"
want_delete_this_save = "このセーブデータを削除してもよろしいですか？"
world_context_is_null = "ワールドコンテキストに未バインドです。"
world_name = "ワールド名"
world_name_prefix = ["静かな", "神秘的な", "古びた", "荒廃した", "青々とした", "神聖な", "幻想的な", "眠っている", "穏やかな", "寂しい", "輝く", "不思議な", "荒野の", "栄える", "かすかな光の", "永遠な", "霧の", "魅惑的な", "荒々しい", "ファンタジックな", "優しい", "流れる光の", "暗がりの", "きらめく", "夢幻的な", "だらけた", "燃えるような", "さっぱりとした", "儚い", "深い", "色とりどりの", "繊細な", "柔らかい", "浮遊する", "星が落ちる", "月が沈む", "風がささやく", "炎が舞う", "氷が凍る", "もちもちした", "燃え尽きた", "霜の花の", "霧に隠れた", "星が回る", "竜の骸の", "神の領域", "悪魔の淵", "霊的な調べの", "幻の昼の", "永夜の", "隕石の", "魂がよぶ", "万物の", "万象の", "天蓋の", "深淵の", "オーロラの", "雷鳴の", "潮の満ち引きの", "騒がしい"]
world_name_suffix = ["大陸", "海洋", "遺跡", "星々", "秘境", "伝説", "響き", "幻境", "庭園", "森", "川", "山脈", "星空", "夢境", "空", "深淵", "クリスタル", "陶磁器", "楽器", "峡谷", "鍾乳洞", "氷河", "オアシス", "神の領域", "悪魔の境地", "潮の満ち引き", "夜風", "朝霧", "蛍火", "風鈴", "詩篇", "絵巻", "歌謡", "琥珀", "瑠璃", "瑪瑙", "珊瑚", "霊的な領域", "星の軌道", "月の洞窟", "竜の巣", "エルフの谷", "ミント", "幻の海", "迷いの森", "永夜の城", "隕石の台", "魂の塚", "雲の境地", "霧の島", "霊の墟", "聖壇", "悪魔の殿", "星間船", "浮島", "空の島", "霊泉", "幻鏡", "神託", "悪魔の言葉", "古木", "秘泉", "ルーン陣", "ポータル", "忘れられた土地", "ささやきの森", "砕けた天蓋"]
fly_enable = "飛行を有効にしました。"
fly_disable = "飛行を無効にしました。"
configuration_commit_success = "設定の保存に成功しました。"
configuration_commit_fail = "設定の保存に失敗しました。"
configuration_update = "設定「{}」を{}に変更しました。"
entry_cannot_found_in_configuration_file = "設定ファイルにエントリ「{}」が見つかりません。"
tile_debug_info = "ブロック座標 ({},{}) チャンク内座標 ({},{}) 湿度 {:.2f} 気温 {:.2f} 浸食 {:.2f} 標高 {:.2f} 異形度 {:.2f}"
mouse_position = "マウス座標-ワールド座標({:.2f},{:.2f})"
tile_res_debug_info = "レイヤー: {} ID: {} 硬度: {} 名前: {}"
total_light = "合計光量:(A{},R{},G{},B{})"
no_biome_was_found = "バイオーム{}が見つかりませんでした。"
biome_has_found = "最も近いバイオーム{}は({},{})に位置しています。"
scancode_unknown = "不明なScanCodeです。"
hook_create_duplicate = "重複するコマンドフックの作成を試みました。"
hook_add_duplicate = "重複するコマンドフックの追加を試みました。"
hook_add_success = "コマンドフックの追加に成功しました。ID：{}"
hook_remove_success = "コマンドフックの削除に成功しました。"
hook_id_not_exist = "ID{}のコマンドフックが存在しない、またはフックが設定（Config）スコープです（設定レベルのコマンドフックはエンジンが自動的に管理します）。"
hook_info = "フックID：{}、スコープ：{}、コマンド：{}、スキャンコード：{}"
scancode_hook_not_found = "ScanCode {} に関連付けられたコマンドフックが見つかりません。"
scancode_hook_found_count = "ScanCode {} に関連付けられたコマンドフックが {} 個見つかりました。"