// Auto-generated by GlimmerWorksCli
// Do not edit manually!

#pragma once

// Injected by //@include annotations
#include "toml11/find.hpp"

// Original header files
#include "../mod/Resource.h"
#include "../mod/dataPack/PackDependence.h"
#include "../Box2dFilter.h"
#include "../contributor/Contributor.h"
#include "../lootTable/LootEntry.h"
#include "../mod/PackManifest.h"

namespace toml {
    // Injected by //@content annotations (globally sorted by index)

    template<>
    struct from<glimmer::ResourceRef> {
        static glimmer::ResourceRef from_toml(const value &v) {
            glimmer::ResourceRef r;
            r.SetPackageId(toml::find<std::string>(v, "pack_id"));
            r.SetResourceType(glimmer::ResourceRef::ResolveResourceType(toml::find<std::string>(v, "resource_type")));
            r.SetResourceKey(toml::find<std::string>(v, "resource_key"));
            return r;
        }
    };


    template<>
    struct from<glimmer::VariableDefinition> {
        static glimmer::VariableDefinition from_toml(const value &v) {
            glimmer::VariableDefinition r;
            r.key = toml::find<std::string>(v, "key");
            r.type = glimmer::VariableDefinition::ResolveVariableType(
                toml::find<std::string>(v, "type"));
            if (r.type == glimmer::VariableDefinitionType::INT) {
                r.value = std::to_string(toml::find<int>(v, "value"));
            } else if (r.type == glimmer::VariableDefinitionType::FLOAT) {
                r.value = std::to_string(toml::find<float>(v, "value"));
            } else if (r.type == glimmer::VariableDefinitionType::BOOL) {
                r.value = std::to_string(toml::find<bool>(v, "value"));
            } else if (r.type == glimmer::VariableDefinitionType::REF) {
                auto resourceRef = toml::find<glimmer::ResourceRef>(v, "value");
                ResourceRefMessage refMessage;
                resourceRef.WriteResourceRefMessage(refMessage);
                r.value = refMessage.SerializeAsString();
            } else {
                r.value = toml::find<std::string>(v, "value");
            }
            return r;
        }
    };


    template<>
    struct from<glimmer::Vector2DIResource> {
        static glimmer::Vector2DIResource from_toml(const value &v) {
            glimmer::Vector2DIResource r;
            r.x = toml::find_or<int>(v, "x", 0);
            r.y = toml::find_or<int>(v, "y", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::ColorResource> {
        static glimmer::ColorResource from_toml(const value &v) {
            glimmer::ColorResource r;
            r.a = toml::find_or<uint8_t>(v, "a", 255);
            r.r = toml::find_or<uint8_t>(v, "r", 0);
            r.g = toml::find_or<uint8_t>(v, "g", 0);
            r.b = toml::find_or<uint8_t>(v, "b", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::RectangleShapeResource> {
        static glimmer::RectangleShapeResource from_toml(const value &v) {
            glimmer::RectangleShapeResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.shapeType = toml::find_or<uint8_t>(v, "shape_type", 0);
            r.width = toml::find_or<float>(v, "width", 1.0F);
            r.height = toml::find_or<float>(v, "height", 1.0F);
            return r;
        }
    };

    template<>
    struct from<glimmer::IShapeResource> {
        static glimmer::IShapeResource from_toml(const value &v) {
            glimmer::IShapeResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.shapeType = toml::find_or<uint8_t>(v, "shape_type", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::Vector2DResource> {
        static glimmer::Vector2DResource from_toml(const value &v) {
            glimmer::Vector2DResource r;
            r.x = toml::find_or<float>(v, "x", 0.0F);
            r.y = toml::find_or<float>(v, "y", 0.0F);
            return r;
        }
    };

    template<>
    struct from<glimmer::ResourcePackManifest> {
        static glimmer::ResourcePackManifest from_toml(const value &v) {
            glimmer::ResourcePackManifest r;
            r.description = toml::find<glimmer::ResourceRef>(v, "description");
            r.author = toml::find<std::string>(v, "author");
            r.versionName = toml::find<std::string>(v, "version_name");
            r.versionNumber = toml::find<uint32_t>(v, "version_number");
            r.minGameVersion = toml::find<uint32_t>(v, "min_game_version");
            r.resPack = toml::find<bool>(v, "res_pack");
            r.id = toml::find<std::string>(v, "id");
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            return r;
        }
    };

    template<>
    struct from<glimmer::LootResource> {
        static glimmer::LootResource from_toml(const value &v) {
            glimmer::LootResource r;
            r.mandatory = toml::find<std::vector<glimmer::LootEntry> >(v, "mandatory");
            r.empty_weight = toml::find_or<uint32_t>(v, "empty_weight", 0);
            r.rolls = toml::find_or<uint32_t>(v, "rolls", 1);
            r.pool = toml::find_or<std::vector<glimmer::LootEntry> >(v, "pool", {});
            r.resourceId = toml::find<std::string>(v, "resource_id");
            return r;
        }
    };

    template<>
    struct from<glimmer::Resource> {
        static glimmer::Resource from_toml(const value &v) {
            glimmer::Resource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            return r;
        }
    };

    template<>
    struct from<glimmer::InitialInventoryResource> {
        static glimmer::InitialInventoryResource from_toml(const value &v) {
            glimmer::InitialInventoryResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.addItems = toml::find<std::vector<glimmer::ItemMessageResource> >(v, "add_items");
            return r;
        }
    };

    template<>
    struct from<glimmer::StringResource> {
        static glimmer::StringResource from_toml(const value &v) {
            glimmer::StringResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.value = toml::find<std::string>(v, "value");
            return r;
        }
    };

    template<>
    struct from<glimmer::TilePlacementForbiddenZone> {
        static glimmer::TilePlacementForbiddenZone from_toml(const value &v) {
            glimmer::TilePlacementForbiddenZone r;
            r.offsetX = toml::find_or<float>(v, "offset_x", 1);
            r.offsetY = toml::find_or<float>(v, "offset_y", 1);
            r.width = toml::find_or<float>(v, "width", 1);
            r.height = toml::find_or<float>(v, "height", 1);
            return r;
        }
    };

    template<>
    struct from<glimmer::DataPackManifest> {
        static glimmer::DataPackManifest from_toml(const value &v) {
            glimmer::DataPackManifest r;
            r.author = toml::find<std::string>(v, "author");
            r.versionNumber = toml::find<uint32_t>(v, "version_number");
            r.resPack = toml::find<bool>(v, "res_pack");
            r.id = toml::find<std::string>(v, "id");
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            r.packDependencies = toml::find<std::vector<glimmer::PackDependence> >(v, "pack_dependencies");
            r.versionName = toml::find<std::string>(v, "version_name");
            r.minGameVersion = toml::find<uint32_t>(v, "min_game_version");
            r.description = toml::find<glimmer::ResourceRef>(v, "description");
            return r;
        }
    };

    template<>
    struct from<glimmer::AbilityConfig> {
        static glimmer::AbilityConfig from_toml(const value &v) {
            glimmer::AbilityConfig r;
            r.miningRange = toml::find_or<float>(v, "mining_range", 5);
            r.fumbleProbability = toml::find_or<float>(v, "fumble_probability", 0);
            r.chainMiningRadius = toml::find_or<int>(v, "chain_mining_radius", 0);
            r.enablePrecisionMining = toml::find_or<bool>(v, "enable_precision_mining", false);
            r.miningEfficiency = toml::find_or<float>(v, "mining_efficiency", 0);
            r.mineAbleLayer = toml::find_or<uint8_t>(v, "mine_able_layer", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::PackDependence> {
        static glimmer::PackDependence from_toml(const value &v) {
            glimmer::PackDependence r;
            r.packId = toml::find<std::string>(v, "pack_id");
            r.minVersion = toml::find<uint32_t>(v, "min_version");
            return r;
        }
    };

    template<>
    struct from<glimmer::IBiomeDecoratorResource> {
        static glimmer::IBiomeDecoratorResource from_toml(const value &v) {
            glimmer::IBiomeDecoratorResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.biomeDecoratorType = toml::find_or<uint8_t>(v, "biome_decorator_type", 0);
            r.layerType = toml::find_or<uint8_t>(v, "layer_type", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::RoundedRectangleShapeResource> {
        static glimmer::RoundedRectangleShapeResource from_toml(const value &v) {
            glimmer::RoundedRectangleShapeResource r;
            r.radius = toml::find_or<float>(v, "radius", 0.0F);
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.shapeType = toml::find_or<uint8_t>(v, "shape_type", 0);
            r.width = toml::find_or<float>(v, "width", 1.0F);
            r.height = toml::find_or<float>(v, "height", 1.0F);
            return r;
        }
    };

    template<>
    struct from<glimmer::Box2dFilter> {
        static glimmer::Box2dFilter from_toml(const value &v) {
            glimmer::Box2dFilter r;
            r.categoryBits = toml::find_or<uint64_t>(v, "category_bits", 0);
            r.maskBits = toml::find_or<uint64_t>(v, "mask_bits", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::VariableConfig> {
        static glimmer::VariableConfig from_toml(const value &v) {
            glimmer::VariableConfig r;
            r.definition = toml::find<std::vector<glimmer::VariableDefinition> >(v, "definition");
            return r;
        }
    };

    template<>
    struct from<glimmer::CircularShapeResource> {
        static glimmer::CircularShapeResource from_toml(const value &v) {
            glimmer::CircularShapeResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.shapeType = toml::find_or<uint8_t>(v, "shape_type", 0);
            r.center = toml::find<glimmer::Vector2DResource>(v, "center");
            r.radius = toml::find_or<float>(v, "radius", 1.0F);
            return r;
        }
    };

    template<>
    struct from<glimmer::AbilityItemResource> {
        static glimmer::AbilityItemResource from_toml(const value &v) {
            glimmer::AbilityItemResource r;
            r.abilityConfig = toml::find_or<glimmer::AbilityConfig>(v, "ability_config", {});
            r.canUseAlone = toml::find_or<bool>(v, "can_use_alone", false);
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            r.description = toml::find_or<glimmer::ResourceRef>(v, "description", {});
            r.texture = toml::find<glimmer::ResourceRef>(v, "texture");
            r.ability = toml::find<std::string>(v, "ability");
            return r;
        }
    };

    template<>
    struct from<glimmer::TileResource> {
        static glimmer::TileResource from_toml(const value &v) {
            glimmer::TileResource r;
            r.description = toml::find_or<glimmer::ResourceRef>(v, "description", {});
            r.texture = toml::find<glimmer::ResourceRef>(v, "texture");
            r.hardness = toml::find_or<float>(v, "hardness", 1.0F);
            r.physicsType = toml::find_or<uint8_t>(v, "physics_type", 0);
            r.layerType = toml::find_or<uint8_t>(v, "layer_type", 0);
            r.allowCrossLayerPlacement = toml::find_or<bool>(v, "allow_cross_layer_placement", false);
            r.lightTransmissionColor = toml::find_or<glimmer::ResourceRef>(v, "light_transmission_color", {});
            r.emissionRadius = toml::find_or<float>(v, "emission_radius", 0.0F);
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            r.customLootTable = toml::find_or<bool>(v, "custom_loot_table", false);
            r.placeSfx = toml::find<glimmer::ResourceRef>(v, "place_sfx");
            r.emissionColor = toml::find_or<glimmer::ResourceRef>(v, "emission_color", {});
            r.allowChainMining = toml::find_or<bool>(v, "allow_chain_mining", false);
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.lootTable = toml::find_or<glimmer::ResourceRef>(v, "loot_table", {});
            r.breakSfx = toml::find<glimmer::ResourceRef>(v, "break_sfx");
            return r;
        }
    };

    template<>
    struct from<glimmer::BiomeResource> {
        static glimmer::BiomeResource from_toml(const value &v) {
            glimmer::BiomeResource r;
            r.erosion = toml::find_or<float>(v, "erosion", 0.0F);
            r.elevation = toml::find_or<float>(v, "elevation", 0.0F);
            r.strictnessTemperature = toml::find_or<float>(v, "strictness_temperature", 1.0F);
            r.strictnessElevation = toml::find_or<float>(v, "strictness_elevation", 1.0F);
            r.bgm = toml::find<glimmer::ResourceRef>(v, "bgm");
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.decors = toml::find<std::vector<glimmer::ResourceRef> >(v, "decors");
            r.temperature = toml::find_or<float>(v, "temperature", 0.0F);
            r.weirdness = toml::find_or<float>(v, "weirdness", 0.0F);
            r.strictnessHumidity = toml::find_or<float>(v, "strictness_humidity", 1.0F);
            r.strictnessWeirdness = toml::find_or<float>(v, "strictness_weirdness", 1.0F);
            r.strictnessErosion = toml::find_or<float>(v, "strictness_erosion", 1.0F);
            r.humidity = toml::find_or<float>(v, "humidity", 0.0F);
            return r;
        }
    };

    template<>
    struct from<glimmer::TileInfo> {
        static glimmer::TileInfo from_toml(const value &v) {
            glimmer::TileInfo r;
            r.position = toml::find<glimmer::Vector2DIResource>(v, "position");
            r.tile = toml::find<glimmer::ResourceRef>(v, "tile");
            return r;
        }
    };

    template<>
    struct from<glimmer::ComposableItemResource> {
        static glimmer::ComposableItemResource from_toml(const value &v) {
            glimmer::ComposableItemResource r;
            r.texture = toml::find<glimmer::ResourceRef>(v, "texture");
            r.slotSize = toml::find<size_t>(v, "slot_size");
            r.defaultAbilityList = toml::find_or<std::vector<glimmer::ItemMessageResource> >(
                v, "default_ability_list", {});
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            r.description = toml::find_or<glimmer::ResourceRef>(v, "description", {});
            return r;
        }
    };

    template<>
    struct from<glimmer::ItemMessageResource> {
        static glimmer::ItemMessageResource from_toml(const value &v) {
            glimmer::ItemMessageResource r;
            r.item = toml::find<glimmer::ResourceRef>(v, "item");
            r.amount = toml::find_or<uint64_t>(v, "amount", 0);
            r.abilityItemRef = toml::find_or<std::vector<glimmer::ItemMessageResource> >(v, "ability_item_ref", {});
            return r;
        }
    };

    template<>
    struct from<glimmer::LootEntry> {
        static glimmer::LootEntry from_toml(const value &v) {
            glimmer::LootEntry r;
            r.min = toml::find_or<uint32_t>(v, "min", 1);
            r.max = toml::find_or<uint32_t>(v, "max", 1);
            r.mandatory = toml::find_or<bool>(v, "mandatory", false);
            r.item = toml::find<glimmer::ResourceRef>(v, "item");
            r.weight = toml::find_or<uint32_t>(v, "weight", 30);
            return r;
        }
    };

    template<>
    struct from<glimmer::SurfaceBiomeDecoratorResource> {
        static glimmer::SurfaceBiomeDecoratorResource from_toml(const value &v) {
            glimmer::SurfaceBiomeDecoratorResource r;
            r.biomeDecoratorType = toml::find_or<uint8_t>(v, "biome_decorator_type", 0);
            r.layerType = toml::find_or<uint8_t>(v, "layer_type", 0);
            r.tile = toml::find<glimmer::ResourceRef>(v, "tile");
            r.allowAir = toml::find_or<bool>(v, "allow_air", true);
            r.allowWater = toml::find_or<bool>(v, "allow_water", false);
            r.resourceId = toml::find<std::string>(v, "resource_id");
            return r;
        }
    };

    template<>
    struct from<glimmer::MineralBiomeDecoratorResource> {
        static glimmer::MineralBiomeDecoratorResource from_toml(const value &v) {
            glimmer::MineralBiomeDecoratorResource r;
            r.layerType = toml::find_or<uint8_t>(v, "layer_type", 0);
            r.ore = toml::find<glimmer::ResourceRef>(v, "ore");
            r.frequency = toml::find_or<float>(v, "frequency", 0.01F);
            r.oreSpawnMinNoiseThreshold = toml::find_or<float>(v, "ore_spawn_min_noise_threshold", 0.5F);
            r.oreSpawnMaxNoiseThreshold = toml::find_or<float>(v, "ore_spawn_max_noise_threshold", 0.8F);
            r.seedOffset = toml::find_or<int>(v, "seed_offset", 1024);
            r.minSpawnElevation = toml::find_or<float>(v, "min_spawn_elevation", 0.0F);
            r.maxSpawnElevation = toml::find_or<float>(v, "max_spawn_elevation", 0.5F);
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.biomeDecoratorType = toml::find_or<uint8_t>(v, "biome_decorator_type", 0);
            r.noiseType = toml::find<uint8_t>(v, "noise_type");
            r.invertOreSpawnByDepth = toml::find_or<bool>(v, "invert_ore_spawn_by_depth", true);
            return r;
        }
    };

    template<>
    struct from<glimmer::Contributor> {
        static glimmer::Contributor from_toml(const value &v) {
            glimmer::Contributor r;
            r.country = toml::find<std::string>(v, "country");
            r.uuid = toml::find<std::string>(v, "uuid");
            r.name = toml::find<std::string>(v, "name");
            r.displayName = toml::find<glimmer::ResourceRef>(v, "display_name");
            return r;
        }
    };

    template<>
    struct from<glimmer::FillBiomeDecoratorResource> {
        static glimmer::FillBiomeDecoratorResource from_toml(const value &v) {
            glimmer::FillBiomeDecoratorResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.tile = toml::find<glimmer::ResourceRef>(v, "tile");
            r.biomeDecoratorType = toml::find_or<uint8_t>(v, "biome_decorator_type", 0);
            r.layerType = toml::find_or<uint8_t>(v, "layer_type", 0);
            return r;
        }
    };

    template<>
    struct from<glimmer::PackManifest> {
        static glimmer::PackManifest from_toml(const value &v) {
            glimmer::PackManifest r;
            r.id = toml::find<std::string>(v, "id");
            r.name = toml::find<glimmer::ResourceRef>(v, "name");
            r.description = toml::find<glimmer::ResourceRef>(v, "description");
            r.author = toml::find<std::string>(v, "author");
            r.versionName = toml::find<std::string>(v, "version_name");
            r.versionNumber = toml::find<uint32_t>(v, "version_number");
            r.minGameVersion = toml::find<uint32_t>(v, "min_game_version");
            r.resPack = toml::find<bool>(v, "res_pack");
            return r;
        }
    };

    template<>
    struct from<glimmer::RayCastResource> {
        static glimmer::RayCastResource from_toml(const value &v) {
            glimmer::RayCastResource r;
            r.origin = toml::find<glimmer::Vector2DResource>(v, "origin");
            r.translation = toml::find<glimmer::Vector2DResource>(v, "translation");
            r.filter = toml::find<glimmer::Box2dFilter>(v, "filter");
            return r;
        }
    };

    template<>
    struct from<glimmer::MobResource> {
        static glimmer::MobResource from_toml(const value &v) {
            glimmer::MobResource r;
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.isPlayer = toml::find_or<bool>(v, "is_player", false);
            r.movementAcceleration = toml::find_or<float>(v, "movement_acceleration", 6.0F);
            r.friction = toml::find_or<float>(v, "friction", 0.0F);
            r.groundCheckRayCast = toml::find_or<std::vector<
                glimmer::RayCastResource> >(v, "ground_check_ray_cast", {});
            r.airControlFactor = toml::find_or<float>(v, "air_control_factor", 1.0F);
            r.shape = toml::find<glimmer::ResourceRef>(v, "shape");
            r.fixedRotation = toml::find<bool>(v, "fixed_rotation");
            r.tilePlacementForbiddenZone = toml::find_or<glimmer::TilePlacementForbiddenZone>(
                v, "tile_placement_forbidden_zone", {});
            r.jumpForce = toml::find_or<float>(v, "jump_force", 7.5F);
            r.textureOffset = toml::find<glimmer::Vector2DResource>(v, "texture_offset");
            r.density = toml::find_or<float>(v, "density", 0.001F);
            r.texture = toml::find_or<glimmer::ResourceRef>(v, "texture", {});
            r.maxSpeed = toml::find_or<float>(v, "max_speed", 18.0F);
            r.bodyType = toml::find<uint8_t>(v, "body_type");
            r.allowBodySleep = toml::find<bool>(v, "allow_body_sleep");
            r.box2dFilter = toml::find<glimmer::Box2dFilter>(v, "box2d_filter");
            return r;
        }
    };

    template<>
    struct from<glimmer::StructurePlacementConditions> {
        static glimmer::StructurePlacementConditions from_toml(const value &v) {
            glimmer::StructurePlacementConditions r;
            r.processorId = toml::find<std::string>(v, "processor_id");
            r.config = toml::find_or<glimmer::VariableConfig>(v, "config", {});
            return r;
        }
    };

    template<>
    struct from<glimmer::StructureResource> {
        static glimmer::StructureResource from_toml(const value &v) {
            glimmer::StructureResource r;
            r.generatorConfig = toml::find_or<glimmer::VariableConfig>(v, "generator_config", {});
            r.condition = toml::find_or<std::vector<glimmer::StructurePlacementConditions> >(v, "condition", {});
            r.tileInfo = toml::find_or<std::vector<glimmer::TileInfo> >(v, "tile_info", {});
            r.data = toml::find_or<std::vector<glimmer::ResourceRef> >(v, "data", {});
            r.resourceId = toml::find<std::string>(v, "resource_id");
            r.generatorId = toml::find<std::string>(v, "generator_id");
            return r;
        }
    };
}
